name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run wdio
      continue-on-error: true
      env:
        NODE_ENV: test

    - name: Generate Allure report
      run: |
        npm run generateReport

    - name: List existing reports
      id: list_reports
      run: ls ./public/Reports || echo "No reports found"
  
    - name: Create directory for GitHub Pages
      run: mkdir -p ./public/Reports

    - name: Copy Allure report to GitHub Pages directory
      run: |
        id=${{ github.run_id }}
        mkdir -p ./public/Reports/$id
        cp -r reports/allure-report/* ./public/Reports/$id/
  
    - name: Cleanup old reports
      if: steps.list_reports.outputs.id != 'No reports found'
      run: |
        cd ./public/Reports
        ls -d */ | sort -r | tail -n +6 | xargs rm -rf
        cd ../..
 
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        publish_branch: gh-pages
        # publish_dir: ./public/Reports/$id/ 

    # - name: Upload Allure report artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: allureReport
    #     path: reports/allure-report