name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run wdio
      continue-on-error: true
      env:
        NODE_ENV: test

    - name: Generate Allure report
      run: |
        npm run generateReport

    # - name: Create directory for GitHub Pages
    #   run: mkdir -p ./public/Reports

    # - name: Copy Allure report to GitHub Pages directory
    #   run: |
    #     id=${{ github.run_number }}
    #     mkdir -p ./public/Reports/$id
    #     cp -r reports/allure-report/* ./public/Reports/$id/
 
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: reports/allure-results
        gh_pages: gh-pages
        allure_report: reports/allure-report
        allure_history: reports/allure-history
        keep_reports: 300

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        publish_branch: gh-pages
        # publish_dir: ./public/Reports/$id/
        keep_files: true

    # - name: Upload Allure report artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: allureReport
    #     path: reports/allure-report